//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MappingGenerator.Test.MappingGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MappingGeneratorTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MappingGeneratorTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MappingGenerator.Test.MappingGenerator.MappingGeneratorTestCases", typeof(MappingGeneratorTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///using System.Collections.Immutable;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static UserDTO [|Map|](UserEntity entity)
        ///        {
        ///            throw new NotImplementedException();
        ///        }
        ///    }
        ///
        ///    public class BaseDTO
        ///    {
        ///        public virtual int Id {get; set;}
        ///        public int Version {get; set;}
        ///    }
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_PureMappingMethod {
            get {
                return ResourceManager.GetString("_001_PureMappingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///using System.Collections.Immutable;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static UserDTO Map(UserEntity entity)
        ///        {
        ///            return new UserDTO()
        ///            {
        ///                Id = entity.Id,
        ///                Age = entity.Age,
        ///                Debs = entity.Debs.ConvertAll(entityDeb =&gt; new AccountDTO()
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_PureMappingMethod_FIXED {
            get {
                return ResourceManager.GetString("_001_PureMappingMethod_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static TDto [|Map|]&lt;TDto, TEntity&gt;(TEntity entity) where TDto: UserDTO, new() where TEntity: UserEntity
        ///        {
        ///            throw new NotImplementedException();
        ///        }
        ///    }
        ///
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get;  }
        ///        public string  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _002_PureMappingMethodWithGenerics {
            get {
                return ResourceManager.GetString("_002_PureMappingMethodWithGenerics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static TDto Map&lt;TDto, TEntity&gt;(TEntity entity) where TDto: UserDTO, new() where TEntity: UserEntity
        ///        {
        ///            return new TDto()
        ///            {
        ///                Age = entity.Age,
        ///                Debs = entity.Debs.ConvertAll(entityDeb =&gt; new AccountDTO()
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _002_PureMappingMethodWithGenerics_FIXED {
            get {
                return ResourceManager.GetString("_002_PureMappingMethodWithGenerics_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static void [|Map|](UserEntity src, UserDTO dst)
        ///        {
        ///            throw new NotImplementedException();
        ///        }
        ///    }
        ///
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get;  }
        ///        public string LastName { get; private set; }
        ///        public int Age  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _003_MappingFromOneToAnotherParameter {
            get {
                return ResourceManager.GetString("_003_MappingFromOneToAnotherParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static void Map(UserEntity src, UserDTO dst)
        ///        {
        ///            dst.Age = src.Age;
        ///            dst.Debs = src.Debs.ConvertAll(srcDeb =&gt; new AccountDTO()
        ///            {
        ///                BankName = srcDeb.BankName,
        ///                Number = srcDeb.Number
        ///            });
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _003_MappingFromOneToAnotherParameter_FIXED {
            get {
                return ResourceManager.GetString("_003_MappingFromOneToAnotherParameter_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; }
        ///        public string LastName { get; private set; }
        ///        public int Age { get; set; }
        ///        public int Cash { get;}
        ///        public AccountDTO Account { get; private set; }
        ///        public List&lt;AccountDTO&gt; Debs { get; set; }
        ///        public UserSourceD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _004_UpdateThisObjectWithSingleParameterDecomposition {
            get {
                return ResourceManager.GetString("_004_UpdateThisObjectWithSingleParameterDecomposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; }
        ///        public string LastName { get; private set; }
        ///        public int Age { get; set; }
        ///        public int Cash { get;}
        ///        public AccountDTO Account { get; private set; }
        ///        public List&lt;AccountDTO&gt; Debs { get; set; }
        ///        public UserSourceD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _004_UpdateThisObjectWithSingleParameterDecomposition_FIXED {
            get {
                return ResourceManager.GetString("_004_UpdateThisObjectWithSingleParameterDecomposition_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class Person
        ///    {
        ///        public int Age { get; set; }
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///
        ///        public void [|Update|](int age, string firstName, string lastName)
        ///        {
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string _005_UpdateThisObjectWithMultipleParameters {
            get {
                return ResourceManager.GetString("_005_UpdateThisObjectWithMultipleParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class Person
        ///    {
        ///        public int Age { get; set; }
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///
        ///        public void Update(int age, string firstName, string lastName)
        ///        {
        ///            Age = age;
        ///            FirstName = firstName;
        ///            LastName = lastName;
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string _005_UpdateThisObjectWithMultipleParameters_FIXED {
            get {
                return ResourceManager.GetString("_005_UpdateThisObjectWithMultipleParameters_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class Person
        ///    {
        ///        public int Age { get; set; }
        ///        public string Name { get; set; }
        ///
        ///        public void [|Update|](int age, string name)
        ///        {
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string _005_UpdateThisObjectWithTwoParameters {
            get {
                return ResourceManager.GetString("_005_UpdateThisObjectWithTwoParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class Person
        ///    {
        ///        public int Age { get; set; }
        ///        public string Name { get; set; }
        ///
        ///        public void Update(int age, string name)
        ///        {
        ///            Age = age;
        ///            Name = name;
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string _005_UpdateThisObjectWithTwoParameters_FIXED {
            get {
                return ResourceManager.GetString("_005_UpdateThisObjectWithTwoParameters_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; }
        ///        public string LastName { get; private set; }
        ///        public int Age { get; set; }
        ///        public int Cash { get;}
        ///        public AccountDTO Account { get; private set; }
        ///        public List&lt;AccountDTO&gt; Debs { get; set; }
        ///        public UserSourceD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _006_ConstructorWithSingleParameterDecomposition {
            get {
                return ResourceManager.GetString("_006_ConstructorWithSingleParameterDecomposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; }
        ///        public string LastName { get; private set; }
        ///        public int Age { get; set; }
        ///        public int Cash { get;}
        ///        public AccountDTO Account { get; private set; }
        ///        public List&lt;AccountDTO&gt; Debs { get; set; }
        ///        public UserSourceD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _006_ConstructorWithSingleParameterDecomposition_FIXED {
            get {
                return ResourceManager.GetString("_006_ConstructorWithSingleParameterDecomposition_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; }
        ///        public string LastName { get; private set; }
        ///        public int Age { get; set; }
        ///        public int Cash { get;}
        ///        public AccountDTO Account { get; private set; }
        ///        public List&lt;AccountDTO&gt; Debs { get; set; }
        ///        public UserSourceD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _007_ConstructorWithMultipleParameters {
            get {
                return ResourceManager.GetString("_007_ConstructorWithMultipleParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; }
        ///        public string LastName { get; private set; }
        ///        public int Age { get; set; }
        ///        public int Cash { get;}
        ///        public AccountDTO Account { get; private set; }
        ///        public List&lt;AccountDTO&gt; Debs { get; set; }
        ///        public UserSourceD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _007_ConstructorWithMultipleParameters_FIXED {
            get {
                return ResourceManager.GetString("_007_ConstructorWithMultipleParameters_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class Model1Vm
        ///    {
        ///        public int Id { get; set; }
        ///        public List&lt;Model2Vm&gt; Model2s { get; set; }
        ///
        ///        public Model1Vm [|Map|](Model1 src)
        ///        {
        ///            throw new NotImplementedException();
        ///        }
        ///    }
        ///
        ///    public class Model2Vm
        ///    {
        ///        public int Id { get; set; }
        ///        public Model1Vm Model1 { get; set; }
        ///
        ///        public string L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _008_StopRecursingMapping {
            get {
                return ResourceManager.GetString("_008_StopRecursingMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class Model1Vm
        ///    {
        ///        public int Id { get; set; }
        ///        public List&lt;Model2Vm&gt; Model2s { get; set; }
        ///
        ///        public Model1Vm Map(Model1 src)
        ///        {
        ///            return new Model1Vm()
        ///            {
        ///                Id = src.Id,
        ///                Model2s = src.Model2s.ConvertAll(srcModel2 =&gt; new Model2Vm()
        ///                {
        ///                    Id = srcModel2.Id,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _008_StopRecursingMapping_Fixed {
            get {
                return ResourceManager.GetString("_008_StopRecursingMapping_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static UserDTO [|Map|](UserDTO old)
        ///        {
        ///            throw new NotImplementedException();
        ///        }
        ///    }
        ///
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; }
        ///        public string LastName { get; private set; }
        ///        public int Age { get; set; }
        ///        public int Cash { g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _009_IdentityFunctionMapping {
            get {
                return ResourceManager.GetString("_009_IdentityFunctionMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static UserDTO Map(UserDTO old)
        ///        {
        ///            return new UserDTO()
        ///            {
        ///                Age = old.Age,
        ///                Debs = old.Debs.ConvertAll(oldDeb =&gt; oldDeb.Clone() as AccountDTO),
        ///                Source = new UserSourceDTO(providerName: old.Source.ProviderName, providerAddress: old [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _009_IdentityFunctionMapping_FIXED {
            get {
                return ResourceManager.GetString("_009_IdentityFunctionMapping_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static long [|Map|](long old)
        ///        {
        ///            throw new NotImplementedException();
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string _010_IdentityFunctionMappingForSimpleType {
            get {
                return ResourceManager.GetString("_010_IdentityFunctionMappingForSimpleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static long Map(long old)
        ///        {
        ///            return old;
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string _010_IdentityFunctionMappingForSimpleType_FIXED {
            get {
                return ResourceManager.GetString("_010_IdentityFunctionMappingForSimpleType_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static List&lt;UserDTO&gt; [|Map|](List&lt;UserDTO&gt; old)
        ///        {
        ///            throw new NotImplementedException();
        ///        }
        ///    }
        ///
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; }
        ///        public string LastName { get; private set; }
        ///        public int Age { get; set; }
        ///        public  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _011_IdentityFunctionMappingForCollection {
            get {
                return ResourceManager.GetString("_011_IdentityFunctionMappingForCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static List&lt;UserDTO&gt; Map(List&lt;UserDTO&gt; old)
        ///        {
        ///            return old.ConvertAll(oldElement =&gt; new UserDTO()
        ///            {
        ///                Age = oldElement.Age,
        ///                Debs = oldElement.Debs.ConvertAll(oldElementDeb =&gt; oldElementDeb.Clone() as AccountDTO),
        ///                Source = new User [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _011_IdentityFunctionMappingForCollection_FIXED {
            get {
                return ResourceManager.GetString("_011_IdentityFunctionMappingForCollection_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity.X
        ///{
        ///    public class XX
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public class YY
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public static class Mapper{
        ///
        ///        public static List&lt;YY&gt; [|Map|](List&lt;XX&gt; categories)
        ///        {
        ///            throw new NotImplementedException();
        ///        }
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _012_CollectionMappingWithSingularLambdaParameterName {
            get {
                return ResourceManager.GetString("_012_CollectionMappingWithSingularLambdaParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity.X
        ///{
        ///    public class XX
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public class YY
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public static class Mapper{
        ///
        ///        public static List&lt;YY&gt; Map(List&lt;XX&gt; categories)
        ///        {
        ///            return categories.ConvertAll(category =&gt; new YY()
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _012_CollectionMappingWithSingularLambdaParameterName_FIXED {
            get {
                return ResourceManager.GetString("_012_CollectionMappingWithSingularLambdaParameterName_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity.X
        ///{
        ///    public class XX
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public class ZZ
        ///    {
        ///        public int CategoryId { get; set; }
        ///        public string CategoryName { get; set; }
        ///    }
        ///
        ///    public static class Mapper{
        ///
        ///        public static List&lt;ZZ&gt; [|MapNew|](List&lt;XX&gt; categories)
        ///        {
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _013_CollectionMappingWithPrefixedLambdaParameterName {
            get {
                return ResourceManager.GetString("_013_CollectionMappingWithPrefixedLambdaParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity.X
        ///{
        ///    public class XX
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public class ZZ
        ///    {
        ///        public int CategoryId { get; set; }
        ///        public string CategoryName { get; set; }
        ///    }
        ///
        ///    public static class Mapper{
        ///
        ///        public static List&lt;ZZ&gt; MapNew(List&lt;XX&gt; categories)
        ///        {
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _013_CollectionMappingWithPrefixedLambdaParameterName_FIXED_ {
            get {
                return ResourceManager.GetString("_013_CollectionMappingWithPrefixedLambdaParameterName_FIXED_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity.X
        ///{
        ///    public class XX
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public class ZZ
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public static class Mapper{
        ///
        ///        public static List&lt;ZZ&gt; [|MapNew|](List&lt;XX&gt; dictionary)
        ///        {
        ///            throw n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _014_CollectionMappingWithGenericName {
            get {
                return ResourceManager.GetString("_014_CollectionMappingWithGenericName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity.X
        ///{
        ///    public class XX
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public class ZZ
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public static class Mapper{
        ///
        ///        public static List&lt;ZZ&gt; MapNew(List&lt;XX&gt; dictionary)
        ///        {
        ///            return dict [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _014_CollectionMappingWithGenericName_FIXED {
            get {
                return ResourceManager.GetString("_014_CollectionMappingWithGenericName_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity.X
        ///{
        ///    public class XX
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public class ZZ
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public static class Mapper{
        ///
        ///        public static List&lt;ZZ&gt; [|MapNew|](List&lt;XX&gt; usersList)
        ///        {
        ///            throw ne [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _015_CollectionMappingWithPostfixGenericName {
            get {
                return ResourceManager.GetString("_015_CollectionMappingWithPostfixGenericName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity.X
        ///{
        ///    public class XX
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public class ZZ
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public static class Mapper{
        ///
        ///        public static List&lt;ZZ&gt; MapNew(List&lt;XX&gt; usersList)
        ///        {
        ///            return users [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _015_CollectionMappingWithPostfixGenericName_FIXED {
            get {
                return ResourceManager.GetString("_015_CollectionMappingWithPostfixGenericName_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity.X
        ///{
        ///    public class XX
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public class YY
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public static class Mapper{
        ///
        ///        public static List&lt;YY&gt; [|Map|](List&lt;XX&gt; people)
        ///        {
        ///            throw new NotImplementedException();
        ///        }
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _016_CollectionMappingWithIrregularSingularLambdaParameterName {
            get {
                return ResourceManager.GetString("_016_CollectionMappingWithIrregularSingularLambdaParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity.X
        ///{
        ///    public class XX
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public class YY
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public static class Mapper{
        ///
        ///        public static List&lt;YY&gt; Map(List&lt;XX&gt; people)
        ///        {
        ///            return people.ConvertAll(person =&gt; new YY()
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _016_CollectionMappingWithIrregularSingularLambdaParameterName_FIXED {
            get {
                return ResourceManager.GetString("_016_CollectionMappingWithIrregularSingularLambdaParameterName_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity.X
        ///{
        ///    public class XX
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public class YY
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public static class Mapper{
        ///
        ///        public static List&lt;YY&gt; [|Map|](List&lt;XX&gt; relatedPeople)
        ///        {
        ///            throw new NotImplementedException();
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _017_CollectionMappingWithIrregularCamelCaseSingularLambdaParameterName {
            get {
                return ResourceManager.GetString("_017_CollectionMappingWithIrregularCamelCaseSingularLambdaParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity.X
        ///{
        ///    public class XX
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public class YY
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public static class Mapper{
        ///
        ///        public static List&lt;YY&gt; Map(List&lt;XX&gt; relatedPeople)
        ///        {
        ///            return relatedPeople.ConvertAll(relatedPerson =&gt; n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _017_CollectionMappingWithIrregularCamelCaseSingularLambdaParameterName_FIXED {
            get {
                return ResourceManager.GetString("_017_CollectionMappingWithIrregularCamelCaseSingularLambdaParameterName_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity.X
        ///{
        ///    public class XX
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public class ZZ
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public static class Mapper{
        ///
        ///        public static List&lt;ZZ&gt; [|MapNew|](List&lt;XX&gt; userList)
        ///        {
        ///            throw new [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _018_CollectionMappingWithPostfixGenericNameInSingular {
            get {
                return ResourceManager.GetString("_018_CollectionMappingWithPostfixGenericNameInSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity.X
        ///{
        ///    public class XX
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public class ZZ
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public static class Mapper{
        ///
        ///        public static List&lt;ZZ&gt; MapNew(List&lt;XX&gt; userList)
        ///        {
        ///            return userLi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _018_CollectionMappingWithPostfixGenericNameInSingular_FIXED {
            get {
                return ResourceManager.GetString("_018_CollectionMappingWithPostfixGenericNameInSingular_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Microsoft.AspNet.Identity.EntityFramework;
        ///using System;
        ///
        ///namespace TestAutoMapper
        ///{
        ///    public static class ExternalUserTest
        ///    {
        ///        public static ApplicationUserEntity [|ToEntity|](this UserModel model)
        ///        {
        ///           throw new NotImplementedException();
        ///        }
        ///    }
        ///
        ///    public class UserModel
        ///    {
        ///        public string NewProperty1 { get; set; }
        ///        public string NewProperty2 { get; set; }
        ///
        ///        public virtual string Email { get; set; }
        ///
        ///        public vi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _019_MappingPropertiesInheritedFromLibraryClass {
            get {
                return ResourceManager.GetString("_019_MappingPropertiesInheritedFromLibraryClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Microsoft.AspNet.Identity.EntityFramework;
        ///using System;
        ///
        ///namespace TestAutoMapper
        ///{
        ///    public static class ExternalUserTest
        ///    {
        ///        public static ApplicationUserEntity ToEntity(this UserModel model)
        ///        {
        ///            return new ApplicationUserEntity()
        ///            {
        ///                NewProperty1 = model.NewProperty1,
        ///                NewProperty2 = model.NewProperty2,
        ///                Email = model.Email,
        ///                EmailConfirmed = model.EmailConfirmed,
        ///                Pas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _019_MappingPropertiesInheritedFromLibraryClass_FIXED {
            get {
                return ResourceManager.GetString("_019_MappingPropertiesInheritedFromLibraryClass_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Microsoft.AspNet.Identity.EntityFramework;
        ///using System;
        ///
        ///namespace TestAutoMapper
        ///{
        ///    public class UserModel
        ///    {
        ///        public string NewProperty1 { get; set; }
        ///        public string NewProperty2 { get; set; }
        ///
        ///        public virtual string Email { get; set; }
        ///
        ///        public virtual bool EmailConfirmed { get; set; }
        ///
        ///        public virtual string PasswordHash { get; set; }
        ///
        ///        public virtual string SecurityStamp { get; set; }
        ///
        ///        public virtual string PhoneNumber { g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _020_MappingPropertiesInConstructorInheritedFromLibraryClass {
            get {
                return ResourceManager.GetString("_020_MappingPropertiesInConstructorInheritedFromLibraryClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Microsoft.AspNet.Identity.EntityFramework;
        ///using System;
        ///
        ///namespace TestAutoMapper
        ///{
        ///    public class UserModel
        ///    {
        ///        public string NewProperty1 { get; set; }
        ///        public string NewProperty2 { get; set; }
        ///
        ///        public virtual string Email { get; set; }
        ///
        ///        public virtual bool EmailConfirmed { get; set; }
        ///
        ///        public virtual string PasswordHash { get; set; }
        ///
        ///        public virtual string SecurityStamp { get; set; }
        ///
        ///        public virtual string PhoneNumber { g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _020_MappingPropertiesInConstructorInheritedFromLibraryClass_FIXED {
            get {
                return ResourceManager.GetString("_020_MappingPropertiesInConstructorInheritedFromLibraryClass_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static UserDTO [|Map|](string firstName, string lastName)
        ///        {
        ///            throw new NotImplementedException();
        ///        }
        ///    }
        ///
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get;  set;}
        ///        public string LastName { get; set; }
        ///        public int [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _021_MultiParameterPureMappingMethod {
            get {
                return ResourceManager.GetString("_021_MultiParameterPureMappingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static UserDTO Map(string firstName, string lastName)
        ///        {
        ///            return new UserDTO()
        ///            {
        ///                FirstName = firstName,
        ///                LastName = lastName
        ///            };
        ///        }
        ///    }
        ///
        ///    public class UserDTO
        ///    {
        ///        public string F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _021_MultiParameterPureMappingMethod_FIxed {
            get {
                return ResourceManager.GetString("_021_MultiParameterPureMappingMethod_FIxed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity.X
        ///{
        ///    public class XX
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public class YY
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public static class Mapper{
        ///
        ///        public static List&lt;YY&gt; [|Map|](IList&lt;XX&gt; categories)
        ///        {
        ///            throw new NotImplementedException();
        ///        }        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _022_CollectionMappingIListToList {
            get {
                return ResourceManager.GetString("_022_CollectionMappingIListToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///
        ///namespace TestAutoMapper.Identity.X
        ///{
        ///    public class XX
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public class YY
        ///    {
        ///        public int Id { get; set; }
        ///        public string Name { get; set; }
        ///    }
        ///
        ///    public static class Mapper{
        ///
        ///        public static List&lt;YY&gt; Map(IList&lt;XX&gt; categories)
        ///        {
        ///            return categories.Select(category =&gt; new YY()
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _022_CollectionMappingIListToList_Fixed {
            get {
                return ResourceManager.GetString("_022_CollectionMappingIListToList_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static UserDTO [|Map|](UserEntity entity)=&gt; null;
        ///    }
        ///
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get;  }
        ///        public string LastName { get; private set; }
        ///        public int Age { get; set; }
        ///        public int Cash { get;}
        ///        public AccountD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _023_PureLambdaMappingMethod {
            get {
                return ResourceManager.GetString("_023_PureLambdaMappingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static UserDTO Map(UserEntity entity)
        ///        {
        ///            return new UserDTO()
        ///            {
        ///                Age = entity.Age,
        ///                Debs = entity.Debs.ConvertAll(entityDeb =&gt; new AccountDTO()
        ///                {
        ///                    BankName = entityDeb.BankName,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _023_PureLambdaMappingMethod_FIXED {
            get {
                return ResourceManager.GetString("_023_PureLambdaMappingMethod_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static UserDTO [|Map|](UserEntity entity)
        ///    }
        ///
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get;  }
        ///        public string LastName { get; private set; }
        ///        public int Age { get; set; }
        ///        public int Cash { get;}
        ///        public AccountDTO Accou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _024_InvalidSyntaxPureMappingMethod {
            get {
                return ResourceManager.GetString("_024_InvalidSyntaxPureMappingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static UserDTO Map(UserEntity entity)
        ///        {
        ///            return new UserDTO()
        ///            {
        ///                Age = entity.Age,
        ///                Debs = entity.Debs.ConvertAll(entityDeb =&gt; new AccountDTO()
        ///                {
        ///                    BankName = entityDeb.BankName,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _024_InvalidSyntaxPureMappingMethod_FIXED {
            get {
                return ResourceManager.GetString("_024_InvalidSyntaxPureMappingMethod_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public struct Category { }
        ///    public struct Tag { }
        ///    public class CreateProductCommand
        ///    {
        ///        public string Name { get; set; }
        ///
        ///        public decimal Price { get; set; }
        ///
        ///        public Category Category { get; set; }
        ///
        ///        public Tag[] Tags { get; set; }
        ///
        ///        public Product [|ToProduct()|]
        ///        {
        ///           throw new NotImplementedException();
        ///        }
        ///    }
        ///
        ///    public class Prod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _025_ThisObjectToOtherMapping {
            get {
                return ResourceManager.GetString("_025_ThisObjectToOtherMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public struct Category { }
        ///    public struct Tag { }
        ///    public class CreateProductCommand
        ///    {
        ///        public string Name { get; set; }
        ///
        ///        public decimal Price { get; set; }
        ///
        ///        public Category Category { get; set; }
        ///
        ///        public Tag[] Tags { get; set; }
        ///
        ///        public Product ToProduct()
        ///        {
        ///            return new Product(name: this.Name, price: this.Price, category: this.Category, ta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _025_ThisObjectToOtherMapping_FIXED {
            get {
                return ResourceManager.GetString("_025_ThisObjectToOtherMapping_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class Person
        ///    {
        ///        public int Age { get; set; }
        ///        public string Name { get; set; }
        ///
        ///        public void [|Update|](int age)
        ///        {
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _026_UpdateThisObjectWithSingleParameterMethod {
            get {
                return ResourceManager.GetString("_026_UpdateThisObjectWithSingleParameterMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class Person
        ///    {
        ///        public int Age { get; set; }
        ///        public string Name { get; set; }
        ///
        ///        public void Update(int age)
        ///        {
        ///            Age = age;
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _026_UpdateThisObjectWithSingleParameterMethod_FIXED {
            get {
                return ResourceManager.GetString("_026_UpdateThisObjectWithSingleParameterMethod_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class Person
        ///    {
        ///        public int Age { get; set; }
        ///        public string Name { get; set; }
        ///
        ///        public [|Person|](int age)
        ///        {
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _027_ConstructorWithSingleParameter {
            get {
                return ResourceManager.GetString("_027_ConstructorWithSingleParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class Person
        ///    {
        ///        public int Age { get; set; }
        ///        public string Name { get; set; }
        ///
        ///        public Person(int age)
        ///        {
        ///            Age = age;
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _027_ConstructorWithSingleParameter_FIXED {
            get {
                return ResourceManager.GetString("_027_ConstructorWithSingleParameter_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    class ClassA
        ///    {
        ///        public string Property1 { get; set; }
        ///        public string Property2 { get; set; }
        ///        public string Property3 { get; set; }
        ///        public string Property4 { get; set; }
        ///        public string Property5 { get; set; }
        ///        public string Property6 { get; set; }
        ///        public string Property7 { get; set; }
        ///        public string Property8 { get; set; }
        ///        public string Property9 { get; set; } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _028_PrivateUpdateFieldAccessibility {
            get {
                return ResourceManager.GetString("_028_PrivateUpdateFieldAccessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    class ClassA
        ///    {
        ///        public string Property1 { get; set; }
        ///        public string Property2 { get; set; }
        ///        public string Property3 { get; set; }
        ///        public string Property4 { get; set; }
        ///        public string Property5 { get; set; }
        ///        public string Property6 { get; set; }
        ///        public string Property7 { get; set; }
        ///        public string Property8 { get; set; }
        ///        public string Property9 { get; set; } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _028_PrivateUpdateFieldAccessibility_FIXEDy {
            get {
                return ResourceManager.GetString("_028_PrivateUpdateFieldAccessibility_FIXEDy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static UserDTO [|Map|](UserEntity entity)
        ///        {
        ///            throw new NotImplementedException();
        ///        }
        ///
        ///        private static AddressDTO MapAddress(AddressEntity addressEntity)
        ///        {
        ///            return new AddressDTO()
        ///            {
        ///                City = addres [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _029_PureMappingMethodWithCustomConversions {
            get {
                return ResourceManager.GetString("_029_PureMappingMethodWithCustomConversions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static UserDTO Map(UserEntity entity)
        ///        {
        ///            return new UserDTO()
        ///            {
        ///                Age = entity.Age,
        ///                Debs = entity.Debs.ConvertAll(entityDeb =&gt; new AccountDTO()
        ///                {
        ///                    BankName = entityDeb.BankName,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _029_PureMappingMethodWithCustomConversions_FIXED {
            get {
                return ResourceManager.GetString("_029_PureMappingMethodWithCustomConversions_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    class ClassA
        ///    {
        ///        public string Property1 { get; set; }
        ///        public string Property2 { get; set; }
        ///        public string Property3 { get; set; }
        ///        public string Property4 { get; set; }
        ///        public string Property5 { get; set; }
        ///        public string Property6 { get; set; }
        ///        public string Property7 { get; set; }
        ///        public string Property8 { get; set; }
        ///        public string Property9 { get; set; } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _030_ConstructorUpdateFieldAccessibility {
            get {
                return ResourceManager.GetString("_030_ConstructorUpdateFieldAccessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    class ClassA
        ///    {
        ///        public string Property1 { get; set; }
        ///        public string Property2 { get; set; }
        ///        public string Property3 { get; set; }
        ///        public string Property4 { get; set; }
        ///        public string Property5 { get; set; }
        ///        public string Property6 { get; set; }
        ///        public string Property7 { get; set; }
        ///        public string Property8 { get; set; }
        ///        public string Property9 { get; set; } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _030_ConstructorUpdateFieldAccessibility_FIXED {
            get {
                return ResourceManager.GetString("_030_ConstructorUpdateFieldAccessibility_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper: BaseMapper
        ///    {
        ///        public static UserDTO [|Map|](UserEntity entity)
        ///        {
        ///            throw new NotImplementedException();
        ///        }
        ///    }
        ///
        ///    public class BaseMapper
        ///    {
        ///        protected static AddressDTO MapAddress(AddressEntity addressEntity)
        ///        {
        ///            return new A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _031_PureMappingMethodWithInheritedCustomConversions {
            get {
                return ResourceManager.GetString("_031_PureMappingMethodWithInheritedCustomConversions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper: BaseMapper
        ///    {
        ///        public static UserDTO Map(UserEntity entity)
        ///        {
        ///            return new UserDTO()
        ///            {
        ///                Age = entity.Age,
        ///                Debs = entity.Debs.ConvertAll(entityDeb =&gt; new AccountDTO()
        ///                {
        ///                    BankName = entityDeb.B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _031_PureMappingMethodWithInheritedCustomConversions_FIXED {
            get {
                return ResourceManager.GetString("_031_PureMappingMethodWithInheritedCustomConversions_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    class ClassA
        ///    {
        ///        public string Property1 { get; set; }
        ///        public string Property2 { get; set; }
        ///        public string Property3 { get; set; }
        ///        public string Property4 { get; set; }
        ///        public string Property5 { get; set; }
        ///        public string Property6 { get; set; }
        ///        public string Property7 { get; set; }
        ///        public string Property8 { get; set; }
        ///        public string Property9 { get; set; } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _032_PubliclyUpdateFieldAccessibility {
            get {
                return ResourceManager.GetString("_032_PubliclyUpdateFieldAccessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    class ClassA
        ///    {
        ///        public string Property1 { get; set; }
        ///        public string Property2 { get; set; }
        ///        public string Property3 { get; set; }
        ///        public string Property4 { get; set; }
        ///        public string Property5 { get; set; }
        ///        public string Property6 { get; set; }
        ///        public string Property7 { get; set; }
        ///        public string Property8 { get; set; }
        ///        public string Property9 { get; set; } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _032_PubliclyUpdateFieldAccessibility_FIXED {
            get {
                return ResourceManager.GetString("_032_PubliclyUpdateFieldAccessibility_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///using System.Collections.Immutable;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static UserDTO [|Map|](UserEntity entity)
        ///        {
        ///            throw new NotImplementedException();
        ///        }
        ///    }
        ///
        ///    public class UserDTO
        ///    {
        ///        public string FirstName;
        ///        public string LastName;
        ///        public int Age; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _033_PureMappingMethodWithFields {
            get {
                return ResourceManager.GetString("_033_PureMappingMethodWithFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///using System.Collections.Immutable;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static UserDTO Map(UserEntity entity)
        ///        {
        ///            return new UserDTO()
        ///            {
        ///                FirstName = entity.FirstName,
        ///                LastName = entity.LastName,
        ///                Age = entity.Age,
        ///                Cash  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _033_PureMappingMethodWithFields_FIXED {
            get {
                return ResourceManager.GetString("_033_PureMappingMethodWithFields_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    class ClassA: BaseClassA
        ///    {
        ///        public string Field1;
        ///        public string Field2;
        ///        public string Field3;
        ///        public string Field4;
        ///        public string BaseField1;
        ///        public string BaseField2;
        ///        public string BaseField3;
        ///        public string BaseField4;
        ///        public string ExtraField1;
        ///        protected string ExtraField2;
        ///        private string ExtraField3;
        ///        internal string ExtraFiel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _034_PubliclyUpdateFieldAccessibilityForFields {
            get {
                return ResourceManager.GetString("_034_PubliclyUpdateFieldAccessibilityForFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    class ClassA: BaseClassA
        ///    {
        ///        public string Field1;
        ///        public string Field2;
        ///        public string Field3;
        ///        public string Field4;
        ///        public string BaseField1;
        ///        public string BaseField2;
        ///        public string BaseField3;
        ///        public string BaseField4;
        ///        public string ExtraField1;
        ///        protected string ExtraField2;
        ///        private string ExtraField3;
        ///        internal string ExtraFiel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _034_PubliclyUpdateFieldAccessibilityForFields_FIXED {
            get {
                return ResourceManager.GetString("_034_PubliclyUpdateFieldAccessibilityForFields_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    class ClassA: BaseClassA
        ///    {
        ///        public string Field1;
        ///        public string Field2;
        ///        public string Field3;
        ///        public string Field4;
        ///        public string BaseField1;
        ///        public string BaseField2;
        ///        public string BaseField3;
        ///        public string BaseField4;
        ///        public string ExtraField1;
        ///        protected string ExtraField2;
        ///        private string ExtraField3;
        ///        internal string ExtraFiel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _035_ConstructorInitializeFIelds {
            get {
                return ResourceManager.GetString("_035_ConstructorInitializeFIelds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    class ClassA: BaseClassA
        ///    {
        ///        public string Field1;
        ///        public string Field2;
        ///        public string Field3;
        ///        public string Field4;
        ///        public string BaseField1;
        ///        public string BaseField2;
        ///        public string BaseField3;
        ///        public string BaseField4;
        ///        public string ExtraField1;
        ///        protected string ExtraField2;
        ///        private string ExtraField3;
        ///        internal string ExtraFiel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _035_ConstructorInitializeFIelds_FIXED {
            get {
                return ResourceManager.GetString("_035_ConstructorInitializeFIelds_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #nullable enable
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///using System.Collections.Immutable;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static UserDTO [|Map|](UserEntity entity)
        ///        {
        ///            throw new NotImplementedException();
        ///        }
        ///    }
        ///
        ///    public class UserDTO
        ///    {
        ///        public override int Id {get; set;}
        ///        public string FirstN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _036_PureMappingMethodWithNullable {
            get {
                return ResourceManager.GetString("_036_PureMappingMethodWithNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #nullable enable
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///using System.Collections.Immutable;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static UserDTO [|Map|](UserEntity entity)
        ///        {
        ///            return new UserDTO()
        ///            {
        ///                Id = entity.Id,
        ///                FirstName = entity.FirstName,
        ///                MiddleName = entity.MiddleName [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _036_PureMappingMethodWithNullable_FIXED {
            get {
                return ResourceManager.GetString("_036_PureMappingMethodWithNullable_FIXED", resourceCulture);
            }
        }
    }
}
