//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MappingGenerator.Test.MappingGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MappingGeneratorTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MappingGeneratorTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MappingGenerator.Test.MappingGenerator.MappingGeneratorTestCases", typeof(MappingGeneratorTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static UserDTO [|Map|](UserEntity entity)
        ///        {
        ///            throw new NotImplementedException();
        ///        }
        ///    }
        ///
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get;  }
        ///        public string LastName { get; private set; }
        ///        public int Age { get;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_PureMappingMethod {
            get {
                return ResourceManager.GetString("_001_PureMappingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static UserDTO Map(UserEntity entity)
        ///        {
        ///            return new UserDTO()
        ///            {
        ///                Age = entity.Age,
        ///                Debs = entity.Debs.Select(entityDeb =&gt; new AccountDTO()
        ///                {
        ///                    BankName = entityDeb.BankName,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_PureMappingMethod_FIXED {
            get {
                return ResourceManager.GetString("_001_PureMappingMethod_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static TDto [|Map|]&lt;TDto, TEntity&gt;(TEntity entity) where TDto: UserDTO, new() where TEntity: UserEntity
        ///        {
        ///            throw new NotImplementedException();
        ///        }
        ///    }
        ///
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get;  }
        ///        public string  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _002_PureMappingMethodWithGenerics {
            get {
                return ResourceManager.GetString("_002_PureMappingMethodWithGenerics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static TDto Map&lt;TDto, TEntity&gt;(TEntity entity) where TDto: UserDTO, new() where TEntity: UserEntity
        ///        {
        ///            return new TDto()
        ///            {
        ///                Age = entity.Age,
        ///                Debs = entity.Debs.Select(entityDeb =&gt; new AccountDTO()
        ///                {        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _002_PureMappingMethodWithGenerics_FIXED {
            get {
                return ResourceManager.GetString("_002_PureMappingMethodWithGenerics_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static void [|Map|](UserEntity src, UserDTO dst)
        ///        {
        ///            throw new NotImplementedException();
        ///        }
        ///    }
        ///
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get;  }
        ///        public string LastName { get; private set; }
        ///        public int Age  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _003_MappingFromOneToAnotherParameter {
            get {
                return ResourceManager.GetString("_003_MappingFromOneToAnotherParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public static void Map(UserEntity src, UserDTO dst)
        ///        {
        ///            dst.Age = src.Age;
        ///            dst.Debs = src.Debs.Select(srcDeb =&gt; new AccountDTO()
        ///            {
        ///                BankName = srcDeb.BankName,
        ///                Number = srcDeb.Number
        ///            }).ToList();
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _003_MappingFromOneToAnotherParameter_FIXED {
            get {
                return ResourceManager.GetString("_003_MappingFromOneToAnotherParameter_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; }
        ///        public string LastName { get; private set; }
        ///        public int Age { get; set; }
        ///        public int Cash { get;}
        ///        public AccountDTO Account { get; private set; }
        ///        public List&lt;AccountDTO&gt; Debs { get; set; }
        ///        public UserSourceD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _004_UpdateThisObjectWithSingleParameter {
            get {
                return ResourceManager.GetString("_004_UpdateThisObjectWithSingleParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; }
        ///        public string LastName { get; private set; }
        ///        public int Age { get; set; }
        ///        public int Cash { get;}
        ///        public AccountDTO Account { get; private set; }
        ///        public List&lt;AccountDTO&gt; Debs { get; set; }
        ///        public UserSourceD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _004_UpdateThisObjectWithSingleParameter_FIXED {
            get {
                return ResourceManager.GetString("_004_UpdateThisObjectWithSingleParameter_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class 005_UpdateThisObjectWithMultipleParameters
        ///    {
        ///        
        ///    }
        ///}.
        /// </summary>
        internal static string _005_UpdateThisObjectWithMultipleParameters {
            get {
                return ResourceManager.GetString("_005_UpdateThisObjectWithMultipleParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class 005_UpdateThisObjectWithMultipleParameters_FIXED
        ///    {
        ///        
        ///    }
        ///}.
        /// </summary>
        internal static string _005_UpdateThisObjectWithMultipleParameters_FIXED {
            get {
                return ResourceManager.GetString("_005_UpdateThisObjectWithMultipleParameters_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; }
        ///        public string LastName { get; private set; }
        ///        public int Age { get; set; }
        ///        public int Cash { get;}
        ///        public AccountDTO Account { get; private set; }
        ///        public List&lt;AccountDTO&gt; Debs { get; set; }
        ///        public UserSourceD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _006_ConstructorWithSingleParameter {
            get {
                return ResourceManager.GetString("_006_ConstructorWithSingleParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; }
        ///        public string LastName { get; private set; }
        ///        public int Age { get; set; }
        ///        public int Cash { get;}
        ///        public AccountDTO Account { get; private set; }
        ///        public List&lt;AccountDTO&gt; Debs { get; set; }
        ///        public UserSourceD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _006_ConstructorWithSingleParameter_FIXED {
            get {
                return ResourceManager.GetString("_006_ConstructorWithSingleParameter_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; }
        ///        public string LastName { get; private set; }
        ///        public int Age { get; set; }
        ///        public int Cash { get;}
        ///        public AccountDTO Account { get; private set; }
        ///        public List&lt;AccountDTO&gt; Debs { get; set; }
        ///        public UserSourceD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _007_ConstructorWithMultipleParameters {
            get {
                return ResourceManager.GetString("_007_ConstructorWithMultipleParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; }
        ///        public string LastName { get; private set; }
        ///        public int Age { get; set; }
        ///        public int Cash { get;}
        ///        public AccountDTO Account { get; private set; }
        ///        public List&lt;AccountDTO&gt; Debs { get; set; }
        ///        public UserSourceD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _007_ConstructorWithMultipleParameters_FIXED {
            get {
                return ResourceManager.GetString("_007_ConstructorWithMultipleParameters_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class Model1Vm
        ///    {
        ///        public int Id { get; set; }
        ///        public List&lt;Model2Vm&gt; Model2s { get; set; }
        ///
        ///        public Model1Vm [|Map|](Model1 src)
        ///        {
        ///            throw new NotImplementedException();
        ///        }
        ///    }
        ///
        ///    public class Model2Vm
        ///    {
        ///        public int Id { get; set; }
        ///        public Model1Vm Model1 { get; set; }
        ///
        ///        public string L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _008_StopRecursingMapping {
            get {
                return ResourceManager.GetString("_008_StopRecursingMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    public class Model1Vm
        ///    {
        ///        public int Id { get; set; }
        ///        public List&lt;Model2Vm&gt; Model2s { get; set; }
        ///
        ///        public Model1Vm Map(Model1 src)
        ///        {
        ///            return new Model1Vm()
        ///            {
        ///                Id = src.Id,
        ///                Model2s = src.Model2s.Select(srcModel2 =&gt; new Model2Vm()
        ///                {
        ///                    Id = srcModel2.Id,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _008_StopRecursingMapping_Fixed {
            get {
                return ResourceManager.GetString("_008_StopRecursingMapping_Fixed", resourceCulture);
            }
        }
    }
}
