//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MappingGenerator.Test.InvocationScaffolding {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InvocationScaffoldingTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvocationScaffoldingTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MappingGenerator.Test.InvocationScaffolding.InvocationScaffoldingTestCases", typeof(InvocationScaffoldingTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Scaffolding
        ///{
        ///   public static class SampleClass
        ///   {
        ///      public static void DoSth()
        ///      {
        ///          DoSthElse();
        ///      }
        ///
        ///
        ///      public static void DoSthElse(string parameter1, int parameter2)
        ///      {
        ///      }
        ///   }
        ///}.
        /// </summary>
        internal static string _001_MethodInvocationScaffolding_With_RegularArguments {
            get {
                return ResourceManager.GetString("_001_MethodInvocationScaffolding_With_RegularArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Scaffolding
        ///{
        ///   public static class SampleClass
        ///   {
        ///      public static void DoSth()
        ///      {
        ///          DoSthElse(&quot;lorem ipsum&quot;, 32);
        ///      }
        ///
        ///
        ///      public static void DoSthElse(string parameter1, int parameter2)
        ///      {
        ///      }
        ///   }
        ///}.
        /// </summary>
        internal static string _001_MethodInvocationScaffolding_With_RegularArguments_FIXED {
            get {
                return ResourceManager.GetString("_001_MethodInvocationScaffolding_With_RegularArguments_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Scaffolding
        ///{
        ///   public static class SampleClass
        ///   {
        ///      public static void DoSth()
        ///      {
        ///          DoSthElse();
        ///      }
        ///
        ///
        ///      public static void DoSthElse(string parameter1, int parameter2)
        ///      {
        ///      }
        ///   }
        ///}.
        /// </summary>
        internal static string _002_MethodInvocationScaffolding_With_NamedArguments {
            get {
                return ResourceManager.GetString("_002_MethodInvocationScaffolding_With_NamedArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Scaffolding
        ///{
        ///   public static class SampleClass
        ///   {
        ///      public static void DoSth()
        ///      {
        ///          DoSthElse(&quot;lorem ipsum&quot;, 32);
        ///      }
        ///
        ///
        ///      public static void DoSthElse(string parameter1, int parameter2)
        ///      {
        ///      }
        ///   }
        ///}.
        /// </summary>
        internal static string _002_MethodInvocationScaffolding_With_NamedArguments_FIXED {
            get {
                return ResourceManager.GetString("_002_MethodInvocationScaffolding_With_NamedArguments_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Scaffolding
        ///{
        ///   public static class SampleClass
        ///   {
        ///      public static AnotherClass DoSth()
        ///      {
        ///          return new AnotherClass();
        ///      }
        ///
        ///
        ///      public class AnotherClass
        ///      {
        ///            public AnotherClass(string parameter1, int parameter2)
        ///            {
        ///            }
        ///      }
        ///   }
        ///}.
        /// </summary>
        internal static string _003_ConstructorInvocationScaffolding_With_RegularArguments {
            get {
                return ResourceManager.GetString("_003_ConstructorInvocationScaffolding_With_RegularArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Scaffolding
        ///{
        ///   public static class SampleClass
        ///   {
        ///      public static AnotherClass DoSth()
        ///      {
        ///          return new AnotherClass(&quot;lorem ipsum&quot;, 32);
        ///      }
        ///
        ///
        ///      public class AnotherClass
        ///      {
        ///            public AnotherClass(string parameter1, int parameter2)
        ///            {
        ///            }
        ///      }
        ///   }
        ///}.
        /// </summary>
        internal static string _003_ConstructorInvocationScaffolding_With_RegularArguments_FIXED {
            get {
                return ResourceManager.GetString("_003_ConstructorInvocationScaffolding_With_RegularArguments_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Scaffolding
        ///{
        ///   public static class SampleClass
        ///   {
        ///      public static AnotherClass DoSth()
        ///      {
        ///          return new AnotherClass();
        ///      }
        ///
        ///
        ///      public class AnotherClass
        ///      {
        ///            public AnotherClass(string parameter1, int parameter2)
        ///            {
        ///            }
        ///      }
        ///   }
        ///}.
        /// </summary>
        internal static string _004_ConstructorInvocationScaffolding_With_NamedArguments {
            get {
                return ResourceManager.GetString("_004_ConstructorInvocationScaffolding_With_NamedArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Scaffolding
        ///{
        ///   public static class SampleClass
        ///   {
        ///      public static AnotherClass DoSth()
        ///      {
        ///          return new AnotherClass(parameter1: &quot;lorem ipsum&quot;, parameter2: 32);
        ///      }
        ///
        ///
        ///      public class AnotherClass
        ///      {
        ///            public AnotherClass(string parameter1, int parameter2)
        ///            {
        ///            }
        ///      }
        ///   }
        ///}.
        /// </summary>
        internal static string _004_ConstructorInvocationScaffolding_With_NamedArguments_FIXED {
            get {
                return ResourceManager.GetString("_004_ConstructorInvocationScaffolding_With_NamedArguments_FIXED", resourceCulture);
            }
        }
    }
}
