//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MappingGenerator.Test.EmptyInitializationBlock {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmptyInitializationBlockTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmptyInitializationBlockTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MappingGenerator.Test.EmptyInitializationBlock.EmptyInitializationBlockTestCases", typeof(EmptyInitializationBlockTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace MappingGenerator.Test.TestCases
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    class Class1
        ///    {
        ///        public void CreateUser(int age)
        ///        {
        ///            var firstName = &quot;Cezary&quot;;
        ///            var lastName = &quot;Piatek&quot;;
        ///
        ///            var x = new UserDTO()
        ///            [|{
        ///
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_CompleteInitializationBlockWithLocals {
            get {
                return ResourceManager.GetString("_001_CompleteInitializationBlockWithLocals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace MappingGenerator.Test.TestCases
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    class Class1
        ///    {
        ///        public void CreateUser(int age)
        ///        {
        ///            var firstName = &quot;Cezary&quot;;
        ///            var lastName = &quot;Piatek&quot;;
        ///
        ///            var x = new UserDTO()
        ///            {
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_CompleteInitializationBlockWithLocals_FIXED {
            get {
                return ResourceManager.GetString("_001_CompleteInitializationBlockWithLocals_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Linq.Expressions;
        ///
        ///namespace MappingGenerator.Test.EmptyInitializationBlock.TestCasesData
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    public class UserEntity
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    public class Mapper
        ///    {
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _002_CompleteInitializationBlockWithLambdaParameter {
            get {
                return ResourceManager.GetString("_002_CompleteInitializationBlockWithLambdaParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Linq.Expressions;
        ///
        ///namespace MappingGenerator.Test.EmptyInitializationBlock.TestCasesData
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    public class UserEntity
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    public class Mapper
        ///    {
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _002_CompleteInitializationBlockWithLambdaParameter_FIXED {
            get {
                return ResourceManager.GetString("_002_CompleteInitializationBlockWithLambdaParameter_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Linq.Expressions;
        ///
        ///namespace MappingGenerator.Test.EmptyInitializationBlock.TestCasesData
        ///{
        ///    public class Mapper
        ///    {
        ///        public IList&lt;UserDTO&gt; Map(IList&lt;UserEntity&gt; entities)
        ///        {
        ///            return entities.Select((UserEntity x) =&gt; new UserDTO() [|{ }|]).ToList();
        ///        }
        ///    }
        ///
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _003_CompleteInitializationBlockWithSompleLambdaParameter {
            get {
                return ResourceManager.GetString("_003_CompleteInitializationBlockWithSompleLambdaParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Linq.Expressions;
        ///
        ///namespace MappingGenerator.Test.EmptyInitializationBlock.TestCasesData
        ///{
        ///    public class Mapper
        ///    {
        ///        public IList&lt;UserDTO&gt; Map(IList&lt;UserEntity&gt; entities)
        ///        {
        ///            return entities.Select((UserEntity x) =&gt; new UserDTO()
        ///            {
        ///                FirstName = x.FirstName,
        ///                LastName = x.LastName,
        ///                Age = x.Age
        ///            }).ToList();
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _003_CompleteInitializationBlockWithSompleLambdaParameter_FIXED {
            get {
                return ResourceManager.GetString("_003_CompleteInitializationBlockWithSompleLambdaParameter_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace TestAutoMapper
        ///{
        ///    public class Tree
        ///    {
        ///        public string Name { get; set; }
        ///        public Tree Left { get; set; }
        ///        public Tree Right { get; set; }
        ///    }
        ///
        ///    public static class Factory
        ///    {
        ///        public static Tree New()
        ///        {
        ///            return new Tree
        ///            [|{
        ///            }|];
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string _004_CompleteInitializationBlockWithSampleDataRecursiveType {
            get {
                return ResourceManager.GetString("_004_CompleteInitializationBlockWithSampleDataRecursiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace TestAutoMapper
        ///{
        ///    public class Tree
        ///    {
        ///        public string Name { get; set; }
        ///        public Tree Left { get; set; }
        ///        public Tree Right { get; set; }
        ///    }
        ///
        ///    public static class Factory
        ///    {
        ///        public static Tree New()
        ///        {
        ///            return new Tree
        ///            {
        ///                Name = &quot;lorem ipsum&quot;,
        ///                Left = new Tree()
        ///                {
        ///                    Name = &quot;lorem ipsum&quot;,
        ///                    Left = null /* Stop recursive mappin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _004_CompleteInitializationBlockWithSampleDataRecursiveType_FIXED {
            get {
                return ResourceManager.GetString("_004_CompleteInitializationBlockWithSampleDataRecursiveType_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace TestAutoMapper
        ///{
        ///    class DefaultObject
        ///    {
        ///        public string MyProperty { get; set; }
        ///
        ///        public int MyProperty1 { get; set; }
        ///
        ///        public float MyProperty2 { get; set; }
        ///
        ///        public bool MyProperty3 { get; set; }
        ///
        ///        public sbyte MyProperty4 { get; set; }
        ///
        ///        public byte MyProperty5 { get; set; }
        ///
        ///        public char MyProperty6 { get; set; }
        ///
        ///        public CustomEnum MyProperty7 { get; set; }
        ///
        ///        public decimal DecimalProperty { get; set;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _005_CompleteInitializationBlockWithSampleDatComplexType {
            get {
                return ResourceManager.GetString("_005_CompleteInitializationBlockWithSampleDatComplexType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace TestAutoMapper
        ///{
        ///    class DefaultObject
        ///    {
        ///        public string MyProperty { get; set; }
        ///
        ///        public int MyProperty1 { get; set; }
        ///
        ///        public float MyProperty2 { get; set; }
        ///
        ///        public bool MyProperty3 { get; set; }
        ///
        ///        public sbyte MyProperty4 { get; set; }
        ///
        ///        public byte MyProperty5 { get; set; }
        ///
        ///        public char MyProperty6 { get; set; }
        ///
        ///        public CustomEnum MyProperty7 { get; set; }
        ///
        ///        public decimal DecimalProperty { get; set;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _005_CompleteInitializationBlockWithSampleDatComplexType_FIXED {
            get {
                return ResourceManager.GetString("_005_CompleteInitializationBlockWithSampleDatComplexType_FIXED", resourceCulture);
            }
        }
    }
}
