//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MappingGenerator.Test.UseLocalVariablesAsParameters {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UseLocalVariablesTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UseLocalVariablesTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MappingGenerator.Test.UseLocalVariablesAsParameters.UseLocalVariablesTestCases", typeof(UseLocalVariablesTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace MappingGenerator.Test.UseLocalVariablesAsParameters.TestCaseData
        ///{
        ///    public class SampleClass
        ///    {
        ///        public void DoSomething(string firstName, string lastName)
        ///        {
        ///            var age = 33;
        ///            var weight = 80m;
        ///            DoSomethingElse();
        ///        }
        ///
        ///        public void DoSomethingElse(string firstName, string lastName, int age, decimal weight)
        ///        {
        ///
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string _001_UserLocaVariablesToCompleteMethodInvocation {
            get {
                return ResourceManager.GetString("_001_UserLocaVariablesToCompleteMethodInvocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace MappingGenerator.Test.UseLocalVariablesAsParameters.TestCaseData
        ///{
        ///    public class SampleClass
        ///    {
        ///        public void DoSomething(string firstName, string lastName)
        ///        {
        ///            var age = 33;
        ///            var weight = 80m;
        ///            DoSomethingElse(firstName, lastName, age, weight);
        ///        }
        ///
        ///        public void DoSomethingElse(string firstName, string lastName, int age, decimal weight)
        ///        {
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_UserLocaVariablesToCompleteMethodInvocation_Fixed {
            get {
                return ResourceManager.GetString("_001_UserLocaVariablesToCompleteMethodInvocation_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace MappingGenerator.Test.UseLocalVariablesAsParameters.TestCaseData
        ///{
        ///    public class SampleClass
        ///    {
        ///        public void DoSomething(string firstName, string lastName)
        ///        {
        ///            var age = 33;
        ///            var weight = 80m;
        ///            DoSomethingElse(firstName: firstName, lastName: lastName, age: age, weight: weight);
        ///        }
        ///
        ///        public void DoSomethingElse(string firstName, string lastName, int a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_UserLocaVariablesToCompleteMethodInvocationWithNamedParameters_Fixed {
            get {
                return ResourceManager.GetString("_001_UserLocaVariablesToCompleteMethodInvocationWithNamedParameters_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace MappingGenerator.Test.UseLocalVariablesAsParameters.TestCaseData
        ///{
        ///    public class SampleClass
        ///    {
        ///        public void DoSomething(string firstName, string lastName)
        ///        {
        ///            var age = 33;
        ///            var weight = 80m;
        ///            new SampleClass();
        ///        }
        ///    }
        ///
        ///    public class SampleClass
        ///    {
        ///        public SampleClass(string firstName, string lastName, int age, decimal weight)
        ///        {        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _002_UserLocaVariablesToCompleteConstructorInvocation {
            get {
                return ResourceManager.GetString("_002_UserLocaVariablesToCompleteConstructorInvocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace MappingGenerator.Test.UseLocalVariablesAsParameters.TestCaseData
        ///{
        ///    public class SampleClass
        ///    {
        ///        public void DoSomething(string firstName, string lastName)
        ///        {
        ///            var age = 33;
        ///            var weight = 80m;
        ///            new SampleClass(firstName, lastName, age, weight);
        ///        }
        ///    }
        ///
        ///    public class SampleClass
        ///    {
        ///        public SampleClass(string firstName, string lastName, int  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _002_UserLocaVariablesToCompleteConstructorInvocation_Fixed {
            get {
                return ResourceManager.GetString("_002_UserLocaVariablesToCompleteConstructorInvocation_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace MappingGenerator.Test.UseLocalVariablesAsParameters.TestCaseData
        ///{
        ///    public class SampleClass
        ///    {
        ///        public void DoSomething(string firstName, string lastName)
        ///        {
        ///            var age = 33;
        ///            var weight = 80m;
        ///            new SampleClass(firstName: firstName, lastName: lastName, age: age, weight: weight);
        ///        }
        ///    }
        ///
        ///    public class SampleClass
        ///    {
        ///        public SampleClass(strin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _002_UserLocaVariablesToCompleteConstructorInvocationWithNamedParameters_Fixed {
            get {
                return ResourceManager.GetString("_002_UserLocaVariablesToCompleteConstructorInvocationWithNamedParameters_Fixed", resourceCulture);
            }
        }
    }
}
