//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MappingGenerator.Test.ExplicitConversions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExplicitConversionTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExplicitConversionTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MappingGenerator.Test.ExplicitConversions.ExplicitConversionTestCases", typeof(ExplicitConversionTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace MappingGenerator.Test.ExplicitConversions.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public AddressDTO Address { get; set; }
        ///
        ///        public void DoSomething()
        ///        {
        ///            var addressEntity = new AddressEntity();
        ///            this.Address = [|addressEntity|];
        ///        }
        ///    }
        ///
        ///    public class AddressDTO
        ///    {
        ///        public string FlatNo { get; set; }
        ///        public string BuildtingNo { g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_ExplicitConversionForInvalidAssigment {
            get {
                return ResourceManager.GetString("_001_ExplicitConversionForInvalidAssigment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace MappingGenerator.Test.ExplicitConversions.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public AddressDTO Address { get; set; }
        ///
        ///        public void DoSomething()
        ///        {
        ///            var addressEntity = new AddressEntity();
        ///            this.Address = new AddressDTO
        ///            {
        ///                FlatNo = addressEntity.FlatNo,
        ///                BuildtingNo = addressEntity.BuildtingNo,
        ///                Stre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_ExplicitConversionForInvalidAssigment_FIXED {
            get {
                return ResourceManager.GetString("_001_ExplicitConversionForInvalidAssigment_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.Text;
        ///
        ///namespace MappingGenerator.Test.ExplicitConversions.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public AddressDTO Address { get; set; }
        ///
        ///        public ReadOnlyCollection&lt;AddressDTO&gt; DoSomething(IList&lt;AddressEntity&gt; addresses)
        ///        {
        ///            return [|addresses|];
        ///        }
        ///    }
        ///
        ///    public class AddressDTO
        ///    {
        ///        public string FlatNo { get; set; }
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _002_ExplicitConversionForInvalidReturn {
            get {
                return ResourceManager.GetString("_002_ExplicitConversionForInvalidReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.Text;
        ///
        ///namespace MappingGenerator.Test.ExplicitConversions.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public AddressDTO Address { get; set; }
        ///
        ///        public ReadOnlyCollection&lt;AddressDTO&gt; DoSomething(IList&lt;AddressEntity&gt; addresses)
        ///        {
        ///            return addresses.Select(address =&gt; new AddressDTO
        ///            {
        ///                FlatNo = address.FlatNo,
        ///                Buildti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _002_ExplicitConversionForInvalidReturn_FIXED {
            get {
                return ResourceManager.GetString("_002_ExplicitConversionForInvalidReturn_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace MappingGenerator.Test.ExplicitConversions.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public AddressDTO Address { get; set; }
        ///
        ///        public IEnumerable&lt;AddressDTO&gt; DoSomething(AddressEntity address)
        ///        {
        ///            yield return [|address|];
        ///        }
        ///    }
        ///
        ///    public class AddressDTO
        ///    {
        ///        public string FlatNo { get; set; }
        ///        public string BuildtingNo { get; set; }
        ///        public string Street { get; set; }
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _003_ExplicitConversionForInvalidYield {
            get {
                return ResourceManager.GetString("_003_ExplicitConversionForInvalidYield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace MappingGenerator.Test.ExplicitConversions.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public AddressDTO Address { get; set; }
        ///
        ///        public IEnumerable&lt;AddressDTO&gt; DoSomething(AddressEntity address)
        ///        {
        ///            yield return new AddressDTO
        ///            {
        ///                FlatNo = address.FlatNo,
        ///                BuildtingNo = address.BuildtingNo,
        ///                Street = address.Street,
        ///                ZipCode = address.ZipCode [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _003_ExplicitConversionForInvalidYield_FIXED {
            get {
                return ResourceManager.GetString("_003_ExplicitConversionForInvalidYield_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace MappingGenerator.Test.ExplicitConversions.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public AddressDTO Address { get; set; }
        ///
        ///        public UserDTO DoSomething()
        ///        {
        ///            var addressEntity = new AddressEntity();
        ///            return new UserDTO{
        ///                Address = [|addressEntity|]
        ///            }
        ///        }
        ///    }
        ///
        ///    public class UserDTO{
        ///        public AddressDTO Address {get; s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _004_ExplicitConversionForInvalidAssigmentInInitBlock {
            get {
                return ResourceManager.GetString("_004_ExplicitConversionForInvalidAssigmentInInitBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace MappingGenerator.Test.ExplicitConversions.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public AddressDTO Address { get; set; }
        ///
        ///        public UserDTO DoSomething()
        ///        {
        ///            var addressEntity = new AddressEntity();
        ///            return new UserDTO{
        ///                Address = new AddressDTO
        ///                {
        ///                    FlatNo = addressEntity.FlatNo,
        ///                    BuildtingNo = a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _004_ExplicitConversionForInvalidAssigmentInInitBlock_FIXED {
            get {
                return ResourceManager.GetString("_004_ExplicitConversionForInvalidAssigmentInInitBlock_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace MappingGenerator.Test.ExplicitConversions.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public AddressDTO Address { get; set; }
        ///
        ///        public void DoSomething()
        ///        {
        ///            var addressEntity = new AddressEntity();
        ///            this.Address = [|addressEntity|];
        ///        }
        ///    }
        ///
        ///    public class AddressDTO
        ///    {
        ///        public string FlatNo { get; set; }
        ///        public string BuildtingNo { g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _005_ExplicitConversionReUseInstance {
            get {
                return ResourceManager.GetString("_005_ExplicitConversionReUseInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace MappingGenerator.Test.ExplicitConversions.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public AddressDTO Address { get; set; }
        ///
        ///        public void DoSomething()
        ///        {
        ///            var addressEntity = new AddressEntity();
        ///            this.Address.FlatNo = addressEntity.FlatNo;
        ///            this.Address.BuildtingNo = addressEntity.BuildtingNo;
        ///            this.Address.Street = addressEntity.Street;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _005_ExplicitConversionReUseInstance_FIXED {
            get {
                return ResourceManager.GetString("_005_ExplicitConversionReUseInstance_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace MappingGenerator.Test.ExplicitConversions.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public AddressDTO Address { get; set; }
        ///
        ///        public UserDTO DoSomething()
        ///        {
        ///            var addressEntity = new AddressEntity();
        ///            return new UserDTO{
        ///                Address = [|addressEntity|]
        ///            }
        ///        }
        ///    }
        ///
        ///    public class UserDTO{
        ///        public AddressDTO Address {get; s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _006_ExplicitConversionForInvalidAssigmentInInitBlockReuseInstance {
            get {
                return ResourceManager.GetString("_006_ExplicitConversionForInvalidAssigmentInInitBlockReuseInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace MappingGenerator.Test.ExplicitConversions.TestCaseData
        ///{
        ///    public class TestMapper
        ///    {
        ///        public AddressDTO Address { get; set; }
        ///
        ///        public UserDTO DoSomething()
        ///        {
        ///            var addressEntity = new AddressEntity();
        ///            return new UserDTO{
        ///                Address =
        ///                {
        ///                    FlatNo = addressEntity.FlatNo,
        ///                    BuildtingNo = addressEntity.Bu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _006_ExplicitConversionForInvalidAssigmentInInitBlockReuseInstance_FIXED {
            get {
                return ResourceManager.GetString("_006_ExplicitConversionForInvalidAssigmentInInitBlockReuseInstance_FIXED", resourceCulture);
            }
        }
    }
}
