//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MappingGenerator.Test.OnBuildGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OnBuildGeneratorTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OnBuildGeneratorTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MappingGenerator.Test.OnBuildGenerator.OnBuildGeneratorTestCases", typeof(OnBuildGeneratorTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///using MappingGenerator.OnBuildGenerator;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    [MappingInterface]
        ///    public interface ISampleMapper
        ///    {
        ///        UserDTO Map(UserEntity entity);
        ///    }
        ///
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get;  }
        ///        public string LastName { get; private set; }
        ///        public int Age { get; set; }
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_SimpleMappingInterface {
            get {
                return ResourceManager.GetString("_001_SimpleMappingInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // ------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///// ------------------------------------------------------------------------------
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///using MappingGenerator.OnBuildGenera [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_SimpleMappingInterface_TRANSFORMED {
            get {
                return ResourceManager.GetString("_001_SimpleMappingInterface_TRANSFORMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///using MappingGenerator.OnBuildGenerator;
        ///
        ///namespace MappingGenerator.Test.MappingGenerator.TestCaseData
        ///{
        ///    [MappingInterface(TypeMappers = new []{typeof(CustomMappers)})]
        ///    public interface ISampleMapper
        ///    {
        ///        UserDTO Map(UserEntity entity);
        ///    }
        ///
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get;  }
        ///        public string LastName { get; private set; }
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _003_ExternalTypeMappers {
            get {
                return ResourceManager.GetString("_003_ExternalTypeMappers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // ------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///// ------------------------------------------------------------------------------
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///using MappingGenerator.OnBuildGenera [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _003_ExternalTypeMappers_TRANSFORMED {
            get {
                return ResourceManager.GetString("_003_ExternalTypeMappers_TRANSFORMED", resourceCulture);
            }
        }
    }
}
